### ISSUE TITLE
关于对红米4高配版有无继续开发计划。

### ISSUE THREAD

**Issue by fanck0605** [MoKee/android_device_xiaomi_markw#2]
@thune-xiaobai 首先感谢您又继续维护红米4高配版的魔趣！
请问您还有计划继续维护[TWRP的官方源码](https://github.com/TeamWin/android_device_xiaomi_markw)以使其有官方TWRP吗？
以及有意向提交源码至Lineage OS吗？
广大红米4用户真的很需要官方TWRP以及Lineage OS！

**Comment by GuaiYiHu** [comment]
mkp重新起航

**Comment by thune-xiaobai** [comment]
gay虎牛逼

**Comment by fanck0605** [comment]
等待更新哦。

**Comment by lvkuiyong** [comment]
牛逼
